### ISSUE TITLE
Problem with pandoc 2.8

### ISSUE THREAD

**Issue by dbobak** [LaurentRDC/pandoc-pyplot#9]
I'm getting the following error, when using pandoc-pyplot as a filter:

```
pandoc-pyplot: Error in $: Incompatible API versions: encoded with [1,20] but attempted to decode with [1,17,5,4].
CallStack (from HasCallStack):
  error, called at .\Text\Pandoc\JSON.hs:111:48 in pandoc-types-1.17.5.4-1YIMZftZkkF55zFQfWBdlu:Text.Pandoc.JSON
Error running filter pandoc-pyplot:
Filter returned error status 1
make: *** [Makefile:89: result.pdf] Error 83
```

pandoc-pyplot: 2.2.0.0
Pandoc version: 2.8
System: Windows 10 Pro x64, Polish language

**Comment by LaurentRDC** [comment]
Hi @dbobak,

It seems like pandoc-pyplot is currently incompatible with the newest version of pandoc-types (1.20). 

Give me a few hours and I'll have a new version that's compatible with pandoc 2.8 and pandoc-types 1.20.

**Comment by LaurentRDC** [comment]
Version 2.3.0.0 now supports pandoc 2.8+!

Due to breaking changes for pandoc filters, pandoc-pyplor 2.3+ will only support pandoc 2.8+.

Let me know if it works for you so I can close this.

**Comment by dbobak** [comment]
It's working now! Thank you for the quick patch!
